export const useDnData = () =>
  useState('dndData', () => {
    const dnData = {
      background: {
        Acolyte: [
          'I ran away from home at an early age and found refuge in a temple.',
          'My family gave me to a temple, since they were unable or unwilling to care for me.',
          'I grew up in a household with strong religious convictions. Entering the service of one or more gods seemed natural.',
          'An impassioned sermon struck a chord deep in my soul and moved me to serve the faith.',
          'I followed a childhood friend, a respected acquaintance, or someone I loved into religious service.',
          'After encountering a true servant of the gods, I was so inspired that I immediately entered the service of a religious group.',
        ],
        Charlatan: [
          'I was left to my own devices, and my knack for manipulating others helped me survive.',
          'I learned early on that people are gullible and easy to exploit.',
          'I often got in trouble, but I managed to talk my way out of it every time.',
          'I took up with a confidence artist, from whom I learned my craft.',
          'After a charlatan fleeced my family, I decided to learn the trade so I would never be fooled by such deception again.',
          'I was poor or I feared becoming poor, so I learned the tricks I needed to keep myself out of poverty.',
        ],
        Criminal: [
          'I resented authority in my younger days and saw a life of crime as the best way to fight against tyranny and oppression.',
          'Necessity forced me to take up the life, since it was the only way I could survive.',
          "I fell in with a gang of reprobates and ne'er-do-wells, and I learned my specialty from them.",
          'A parent or relative taught me my criminal specialty to prepare me for the family business.',
          "I left home and found a place in a thieves' guild or some other criminal organization.",
          'I was always bored, so I turned to crime to pass the time and discovered I was quite good at it.',
        ],
        Entertainer: [
          'Members of my family made ends meet by performing, so it was fitting for me to follow their example.',
          'I always had a keen insight into other people, enough so that I could make them laugh or cry with my stories or songs.',
          'I ran away from home to follow a minstrel troupe.',
          'I saw a bard perform once, and I knew from that moment on what I was born to do.',
          'I earned coin by performing on street corners and eventually made a name for myself.',
          'A traveling entertainer took me in and taught me the trade.',
        ],
        'Folk Hero': [
          'I learned what was right and wrong from my family.',
          'I was always enamored by tales of heroes and wished I could be something more than ordinary.',
          'I hated my mundane life, so when it was time for someone to step up and do the right thing, I took my chance.',
          "A parent or one of my relatives was an adventurer, and I was inspired by that person's courage.",
          'A mad old hermit spoke a prophecy when I was born, saying that I would accomplish great things.',
          'I have always stood up for those who are weaker than I am.',
        ],
        'Guild Artisan': [
          "I was apprenticed to a master who taught me the guild's business.",
          'I helped a guild artisan keep a secret or complete a task, and in return I was taken on as an apprentice.',
          'One of my family members who belonged to the guild made a place for me.',
          'I was always good with my hands, so I took the opportunity to learn a trade.',
          'I wanted to get away from my home situation and start a new life.',
          'I learned the essentials of my craft from a mentor but had to join the guild to finish my training.',
        ],
        Hermit: [
          'My enemies ruined my reputation, and I fled to the wilds to avoid further disparagement.',
          'I am comfortable with being isolated, as I seek inner peace.',
          'I never liked the people I called my friends, so it was easy for me to strike out on my own.',
          'I felt compelled to forsake my past, but did so with great reluctance, and sometimes I regret making that decision.',
          'I lost everything-my home, my family, my friends. Going it alone was all I could do.',
          "Society's decadence disgusted me, so I decided to leave it behind.",
        ],
        Noble: [
          'I come from an old and storied family, and it fell to me to preserve the family name.',
          'My family has been disgraced, and I intend to clear our name.',
          'My family recently came by its title, and that elevation thrust us into a new and strange world.',
          'My family has a title, but none of my ancestors have distinguished themselves since we gained it.',
          'My family is filled with remarkable people. I hope to live up to their example.',
          "I hope to increase my family's power and influence.",
        ],
        Outlander: [
          'I spent a lot of time in the wilderness as a youngster, and I came to love that way of life.',
          "From a young age, I couldn't abide the stink of the cities and preferred to spend my time in nature.",
          'I came to understand the darkness that lurks in the wilds, and I vowed to combat it.',
          'My people lived on the edges of civilization, and I learned the methods of survival from my family.',
          'After a tragedy I retreated to the wilderness, leaving my old life behind.',
          'My family moved away from civilization, and I learned to adapt to my new environment.',
        ],
        Sage: [
          'I was naturally curious, so I packed up and went to a university to learn more about the world.',
          "My mentor's teachings opened my mind to new possibilities in that field of study.",
          'I was always an avid reader, and I learned much about my favorite topic on my own.',
          'I discovered an old library and pored over the texts I found there. That experience awakened a hunger for more knowledge.',
          'I impressed a wizard who told me I was squandering my talents and should seek out an education to take advantage of my gifts.',
          'One of my parents or a relative gave me a basic education that whetted my appetite, and I left home to build on what I had learned.',
        ],
        Sailor: [
          'I was press-ganged by pirates and forced to serve on their ship until I finally escaped.',
          'I wanted to see the world, so I signed on as a deck-hand for a merchant ship.',
          'One of my relatives was a sailor who took me to sea.',
          'I needed to escape my community quickly, so I stowed away on a ship. When the crew found me, I was forced to work for my passage.',
          'Reavers attacked my community, so I found refuge on a ship until I could seek vengeance.',
          'I had few prospects where I was living, so I left to find my fortune elsewhere.',
        ],
        Soldier: [
          'I joined the militia to help protect my community from monsters.',
          'A relative of mine was a soldier, and I wanted to carry on the family tradition.',
          'The local lord forced me to enlist in the army.',
          'War ravaged my homeland while I was growing up. Fighting was the only life I ever knew.',
          'I wanted fame and fortune, so I joined a mercenary company, selling my sword to the highest bidder.',
          'Invaders attacked my homeland. It was my duty to take up arms in defense of my people.',
        ],
        Urchin: [
          'Wanderlust caused me to leave my family to see the world. I look after myself.',
          'I ran away from a bad situation at home and made my own way in the world.',
          'Monsters wiped out my village, and I was the sole survivor. I had to find a way to survive.',
          'A notorious thief looked after me and other orphans, and we spied and stole to earn our keep.',
          'One day I woke up on the streets, alone and hungry, with no memory of my early childhood.',
          'My parents died, leaving no one to look after me. I raised myself.',
        ],
      },
      class: {
        Barbarian: {
          reason: [
            'My devotion to my people lifted me in battle, making me powerful and dangerous.',
            'The spirits of my ancestors called on me to carry out a great task.',
            'I lost control in battle one day, and it was as if something else was manipulating my body, forcing it to kill every foe I could reach.',
            'I went on a spiritual journey to find myself and instead found a spirit animal to guide, protect, and inspire me.',
            'I was struck by lightning and lived. Afterward, I found a new strength within me that let me push beyond my limitations.',
            'My anger needed to be channeled into battle, or I risked becoming an indiscriminate killer.',
          ],
          quirk: [
            'If you disturb the bones of the dead, you inherit all the troubles that plagued them in life.',
            "Never trust a wizard. They're all devils in disguise, especially the friendly ones.",
            "Dwarves have lost their spirits, and are almost like the undead. That's why they live underground.",
            'Magical things bring trouble. Never sleep with a magic object within ten feet of you.',
            'When you walk through a graveyard, be sure to wear silver, or a ghost might jump into your body.',
            "If an elf looks you in the eyes, she's trying to read your thoughts.",
          ],
        },
        Bard: {
          reason: [
            'I awakened my latent bardic abilities through trial and error.',
            'I was a gifted performer and attracted the attention of a master bard who schooled me in the old techniques.',
            'I joined a loose society of scholars and orators to learn new techniques of performance and magic.',
            'I felt a calling to recount the deeds of champions and heroes, to bring them alive in song and story.',
            'I joined one of the great colleges to learn old lore, the secrets of magic, and the art of performance.',
            'I picked up a musical instrument one day and instantly discovered that I could play it.',
          ],
          quirk: [
            "The time when your comedic song, 'Big Tom's Hijinks'—which, by the way, you thought was brilliant—did not go over well with Big Tom",
            "The matinee performance when a circus's owlbear got loose and terrorized the crowd",
            "When your opening song was your enthusiastic but universally hated rendition of 'Song of the Froghemoth'",
            "The first and last public performance of 'Mirt, Man about Town'",
            'The time on stage when your wig caught fire and you threw it down—which set fire to the stage',
            "When you sat on your lute by mistake during the final stanza of 'Starlight Serenade'",
          ],
        },
        Cleric: {
          reason: [
            'A supernatural being in service to the gods called me to become a divine agent in the world.',
            'I saw the injustice and horror in the world and felt moved to take a stand against them.',
            'My god gave me an unmistakable sign. I dropped everything to serve the divine.',
            "Although I was always devout, it wasn't until I completed a pilgrimage that I knew my true calling.",
            "I used to serve in my religion's bureaucracy but found I needed to work in the world, to bring the message of my faith to the darkest corners of the land.",
            "I realize that my god works through me, and I do as commanded, even though I don't know why I was chosen to serve.",
          ],
          quirk: [
            'An imp offers you counsel. You try to ignore the creature, but sometimes its advice is helpful.',
            'You believe that, in the final analysis, the gods are nothing more than ultrapowerful mortal creatures.',
            'You acknowledge the power of the gods, but you think that most events are dictated by pure chance.',
            'Even though you can work divine magic, you have never truly felt the presence of a divine essence within yourself.',
            'You are plagued by nightmares that you believe are sent by your god as punishment for some unknown transgression.',
            'In times of despair, you feel that you are but a plaything of the gods, and you resent their remoteness.',
          ],
        },
        Druid: {
          reason: [
            "I saw too much devastation in the wild places, too much of nature's splendor ruined by the despoilers. I joined a circle of druids to fight back against the enemies of nature.",
            'I found a place among a group of druids after I fled a catastrophe.',
            'I have always had an affinity for animals, so I explored my talent to see how I could best use it.',
            "I befriended a druid and was moved by druidic teachings. I decided to follow my friend's guidance and give something back to the world.",
            'While I was growing up, I saw spirits all around me-entities no one else could perceive. I sought out the druids to help me understand the visions and communicate with these beings.',
            'I have always felt disgust for creatures of unnatural origin. For this reason, I immersed myself in the study of the druidic mysteries and became a champion of the natural order.',
          ],
          quirk: [
            'Your mentor was a wise treant who taught you to think in terms of years and decades rather than days or months.',
            'You were tutored by a dryad who watched over a slumbering portal to the Abyss. During your training, you were tasked with watching for hidden threats to the world.',
            "Your tutor always interacted with you in the form of a falcon. You never saw the tutor's humanoid form.",
            'You were one of several youngsters who were mentored by an old druid, until one of your fellow pupils betrayed your group and killed your master.',
            'Your mentor has appeared to you only in visions. You have yet to meet this person, and you are not sure such a person exists in mortal form.',
            'Your mentor was a werebear who taught you to treat all living things with equal regard.',
          ],
        },
        Fighter: {
          reason: [
            'I wanted to hone my combat skills, and so I joined a war college.',
            'I squired for a knight who taught me how to fight, care for a steed, and conduct myself with honor. I decided to take up that path for myself.',
            'Horrible monsters descended on my community, killing someone I loved. I took up arms to destroy those creatures and others of a similar nature.',
            'I joined the army and learned how to fight as part of a group.',
            'I grew up fighting, and I refined my talents by defending myself against people who crossed me.',
            'I could always pick up just about any weapon and know how to use it effectively.',
          ],
          quirk: [
            'Elegant. You move with precise grace and total control, never using more energy than you need.',
            'Brutal. Your attacks rain down like hammer blows, meant to splinter bone or send blood flying.',
            'Cunning. You dart in to attack at just the right moment and use small-scale tactics to tilt the odds in your favor.',
            'Effortless. You rarely perspire or display anything other than a stoic expression in battle.',
            'Energetic. You sing and laugh during combat as your spirit soars. You are happiest when you have a foe in front of you and a weapon in hand.',
            'Sinister. You scowl and sneer while fighting, and you enjoy mocking your foes as you defeat them.',
          ],
        },
        Monk: {
          reason: [
            'I was chosen to study at a secluded monastery. There, I was taught the fundamental techniques required to eventually master a tradition.',
            'I sought instruction to gain a deeper understanding of existence and my place in the world.',
            'I stumbled into a portal to the Shadowfell and took refuge in a strange monastery, where I learned how to defend myself against the forces of darkness.',
            'I was overwhelmed with grief after losing someone close to me, and I sought the advice of philosophers to help me cope with my loss.',
            'I could feel that a special sort of power lay within me, so I sought out those who could help me call it forth and master it.',
            'I was wild and undisciplined as a youngster, but then I realized the error of my ways. I applied to a monastery and became a monk as a way to live a life of discipline.',
          ],
          quirk: [
            'Monkey. Quick reflexes and the ability to travel through the treetops are two of the reasons why your order admires the monkey.',
            'Dragon Turtle. The monks of your seaside monastery venerate the dragon turtle, reciting ancient prayers and offering garlands of flowers to honor this living spirit of the sea.',
            'Ki-rin. Your monastery sees its main purpose as watching over and protecting the land in the manner of the ki-rin.',
            'Owlbear. The monks of your monastery revere a family of owlbears and have coexisted with them for generations.',
            'Hydra. Your order singles out the hydra for its ability to unleash several attacks simultaneously.',
            'Dragon. A dragon once laired within your monastery. Its influence remains long after its departure.',
          ],
        },
        Paladin: {
          reason: [
            'A fantastical being appeared before me and called on me to undertake a holy quest.',
            'One of my ancestors left a holy quest unfulfilled, so I intend to finish that work.',
            'The world is a dark and terrible place. I decided to serve as a beacon of light shining out against the gathering shadows.',
            "I served as a paladin's squire, learning all I needed to swear my own sacred oath.",
            'Evil must be opposed on all fronts. I feel compelled to seek out wickedness and purge it from the world.',
            'Becoming a paladin was a natural consequence of my unwavering faith. In taking my vows, I became the holy sword of my religion.',
          ],
          quirk: [
            "Fury. When your anger is roused, you have trouble thinking straight, and you fear you might do something you'll regret.",
            'Pride. Your deeds are noteworthy, and no one takes note of them more often than you.',
            "Lust. You can't resist an attractive face and a pleasant smile.",
            "Envy. You are mindful of what some famous folk have accomplished, and you feel inadequate when your deeds don't compare to theirs.",
            'Despair. You consider the great strength of the enemies you must defeat, and at times you see no way to achieve final victory.',
            "Greed. Regardless of how much glory and treasure you amass, it's never enough for you.",
          ],
        },
        Ranger: {
          reason: [
            'I found purpose while I honed my hunting skills by bringing down dangerous animals at the edge of civilization.',
            'I always had a way with animals, able to calm them with a soothing word and a touch.',
            'I suffer from terrible wanderlust, so being a ranger gave me a reason not to remain in one place for too long.',
            "I have seen what happens when the monsters come out from the dark. I took it upon myself to become the first line of defense against the evils that lie beyond civilization's borders.",
            'I met a grizzled ranger who taught me woodcraft and the secrets of the wild lands.',
            'I served in an army, learning the precepts of my profession while blazing trails and scouting enemy encampments.',
          ],
          quirk: [
            "You seek revenge on nature's behalf for the great transgressions your foe has committed.",
            'Your forebears or predecessors fought these creatures, and so shall you.',
            'You bear no enmity toward your foe. You stalk such creatures as a hunter tracks down a wild animal.',
            'You find your foe fascinating, and you collect books of tales and history concerning it.',
            'You collect tokens of your fallen enemies to remind you of each kill.',
            'You respect your chosen enemy, and you see your battles as a test of respective skills.',
          ],
        },
        Rogue: {
          reason: [
            "I've always been nimble and quick of wit, so I decided to use those talents to help me make my way in the world.",
            'An assassin or a thief wronged me, so I focused my training on mastering the skills of my enemy to better combat foes of that sort.',
            'An experienced rogue saw something in me and taught me several useful tricks.',
            'I decided to turn my natural lucky streak into the basis of a career, though I still realize that improving my skills is essential.',
            'I took up with a group of ruffians who showed me how to get what I want through sneakiness rather than direct confrontation.',
            "I'm a sucker for a shiny bauble or a sack of coins, as long as I can get my hands on it without risking life and limb.",
          ],
          quirk: [
            'Your guilty pleasures is Large gems. Your benefactor is A smuggler kept you from getting caught but lost a valuable shipment in doing so. Now you owe that person an equally valuable favor.',
            'Your guilty pleasures is A smile from a pretty face. Your benefactor is The Beggar King has hidden you from your pursuers many times, in return for future considerations.',
            'Your guilty pleasures is A new ring for your finger. Your benefactor is A magistrate once kept you out of jail in return for information on a powerful crime lord.',
            "Your guilty pleasures is The chance to deflate someone's ego. Your benefactor is Your parents used their savings to bail you out of trouble in your younger days and are now destitute.",
            "Your guilty pleasures is The finest food and drink. Your benefactor is A dragon didn't eat you when it had a chance, and in return you promised to set aside choice pieces of treasure for it.",
            'Your guilty pleasures is Adding to your collection of exotic coins. Your benefactor is A druid once helped you out of a tight spot; now any random animal you see could be that benefactor, perhaps come to claim a return favor.',
          ],
        },
        Sorcerer: {
          reason: [
            'When I was born, all the water in the house froze solid, the milk spoiled, or all the iron turned to copper. My family is convinced that this event was a harbinger of stranger things to come for me.',
            'I suffered a terrible emotional or physical strain, which brought forth my latent magical power. I have fought to control it ever since.',
            "My immediate family never spoke of my ancestors, and when I asked, they would change the subject. It wasn't until I started displaying strange talents that the full truth of my heritage came out.",
            'When a monster threatened one of my friends, I became filled with anxiety. I lashed out instinctively and blasted the wretched thing with a force that came from within me.',
            'Sensing something special in me, a stranger taught me how to control my gift.',
            'After I escaped from a magical conflagration, I realized that though I was unharmed, I was not unchanged. I began to exhibit unusual abilities that I am just beginning to understand.',
          ],
          quirk: [
            'You deliver the verbal components of your spells in the booming voice of a titan.',
            'For a moment after you cast a spell, the area around you grows dark and gloomy.',
            'You sweat profusely while casting a spell and for a few seconds thereafter.',
            'Your hair and garments are briefly buffeted about, as if by a breeze, whenever you call forth a spell.',
            'If you are standing when you cast a spell, you rise six inches into the air and gently float back down.',
            'Illusory blue flames wreathe your head as you begin your casting, then abruptly disappear.',
          ],
        },
        Warlock: {
          reason: [
            'While wandering around in a forbidden place, I encountered an otherworldly being that offered to enter into a pact with me.',
            'I was examining a strange tome I found in an abandoned library when the entity that would become my patron suddenly appeared before me.',
            'I stumbled into the clutches of my patron after I accidentally stepped through a magical doorway.',
            'When I was faced with a terrible crisis, I prayed to any being who would listen, and the creature that answered became my patron.',
            'My future patron visited me in my dreams and offered great power in exchange for my service.',
            'One of my ancestors had a pact with my patron, so that entity was determined to bind me to the same agreement.',
          ],
          quirk: [
            "When directed, you must take immediate action against a specific enemy of your patron. One of your eyes looks the same as one of your patron's eyes.",
            'Your pact tests your willpower; you are required to abstain from alcohol and other intoxicants. Each time you wake up, the small blemish on your face appears in a different place.',
            "At least once a day, you must inscribe or carve your patron's name or symbol on the wall of a building. You display outward symptoms of a disease but suffer no ill effects from it.",
            'You must occasionally conduct bizarre rituals to maintain your pact. Your tongue is an unnatural color.',
            'You can never wear the same outfit twice, since your patron finds such predictability to be boring. You have a vestigial tail.',
            "When you use an eldritch invocation, you must speak your patron's name aloud or risk incurring its displeasure. Your face-element glows in the dark.",
          ],
        },
        Wizard: {
          reason: [
            'An old wizard chose me from among several candidates to serve an apprenticeship.',
            'When I became lost in a forest, a hedge wizard found me, took me in, and taught me the rudiments of magic.',
            'I grew up listening to tales of great wizards and knew I wanted to follow their path. I strove to be accepted at an academy of magic and succeeded.',
            'One of my relatives was an accomplished wizard who decided I was smart enough to learn the craft.',
            'While exploring an old tomb, library, or temple, I found a spellbook. I was immediately driven to learn all I could about becoming a wizard.',
            'I was a prodigy who demonstrated mastery of the arcane arts at an early age. When I became old enough to set out on my own, I did so to learn more magic and expand my power.',
          ],
          quirk: [
            "You will prove that the gods aren't as powerful as folk believe. You have the habit of tapping your foot incessantly, which often annoys those around you.",
            'Immortality is the end goal of your studies. Your memory is quite good, but you have no trouble pretending to be absentminded when it suits your purposes.',
            "If you can fully understand magic, you can unlock its use for all and usher in an era of equality. You never enter a room without looking to see what's hanging from the ceiling.",
            'Magic is a dangerous tool. You use it to protect what you treasure. Your most prized possession is a dead worm that you keep inside a potion vial.',
            'Arcane power must be taken away from those who would abuse it. When you want people to leave you alone, you start talking to yourself. That usually does the trick.',
            'You will become the greatest wizard the world has seen in generations. Your fashion sense and grooming, or more accurately lack thereof, sometimes cause others to assume you are a beggar.',
          ],
        },
      },
      events: {
        adventures: [
          'You nearly died. You have nasty scars on your body, and you are missing an ear, 1d3 fingers, or 1d4 toes.',
          'You suffered a grievous injury. Although the wound healed, it still pains you from time to time.',
          'You were wounded, but in time you fully recovered.',
          'You contracted a disease while exploring a filthy warren. You recovered from the disease, but you have a persistent cough, pockmarks on your skin, or prematurely gray hair.',
          'You were poisoned by a trap or a monster. You recovered, but the next time you must make a saving throw against poison, you make the saving throw with disadvantage.',
          'You lost something of sentimental value to you during your adventure. Remove one trinket from your possessions.',
          'You were terribly frightened by something you encountered and ran away, abandoning your companions to their fate.',
          'You learned a great deal during your adventure. The next time you make an ability check or a saving throw, you have advantage on the roll.',
          'You found some treasure on your adventure. You have 2d6 gp left from your share of it.',
          'You found a considerable amount of treasure on your adventure. You have 1d20+50 gp left from your share of it.',
          "You came across a common magic item (of the DM's choice).",
          'You were charmed or frightened by a spell.',
          'You were injured by the effect of a spell.',
          'You witnessed a powerful spell being cast by a cleric, a druid, a sorcerer, a warlock, or a wizard.',
          "You drank a potion (of the DM's choice).",
          "You found a spell scroll (of the DM's choice) and succeeded in casting the spell it contained.",
          'You were affected by teleportation magic.',
          'You turned invisible for a time.',
          'You identified an illusion for what it was.',
          'You saw a creature being conjured by magic.',
          "Your fortune was read by a diviner. Roll twice on the Life Events table, but don't apply the results. Instead, the DM picks one event as a portent of your future (which might or might not come true).",
          "A friendly wizard gave you a spell scroll containing one cantrip (of the DM's choice).",
          'You saved the life of a commoner, who now owes you a life debt. This individual accompanies you on your travels and performs mundane tasks for you, but will leave if neglected, abused, or imperiled. Determine details about this character by using the supplemental tables and working with your DM.',
          'You found a riding horse.',
          'You found some money. You have 1d20 gp in addition to your regular starting funds.',
          'A relative bequeathed you a simple weapon of your choice.',
          'You found something interesting. You gain one additional trinket.',
          'You once performed a service for a local temple. The next time you visit the temple, you can receive healing up to your hit point maximum.',
          'A friendly alchemist gifted you with a potion of healing or a flask of acid, as you choose.',
          'You found a treasure map.',
          'A distant relative left you a stipend that enables you to live at the comfortable lifestyle for 1d20 years. If you choose to live at a higher lifestyle, you reduce the price of the lifestyle by 2 gp during that time period.',
          'You were ensorcelled by a fey and enslaved for 1d6 years before you escaped.',
          'You saw a demon and ran away before it could do anything to you.',
          "A devil tempted you. Make a DC 10 Wisdom saving throw. On a failed save, your alignment shifts one step toward evil (if it's not evil already), and you start the game with an additional 1d20+50 gp.",
          'You woke up one morning miles from your home, with no idea how you got there.',
          'You visited a holy site and felt the presence of the divine there.',
          'You witnessed a falling red star, a face appearing in the frost, or some other bizarre happening. You are certain that it was an omen of some sort.',
          'You escaped certain death and believe it was the intervention of a god that saved you.',
          'You witnessed a minor miracle.',
          'You explored an empty house and found it to be haunted.',
          'You were briefly possessed. Roll a d6 to determine what kind of creature possessed you: 1, celestial; 2, devil; 3, demon; 4, fey; 5, elemental; 6, undead.',
          'You saw a ghost.',
          'You saw a ghoul feeding on a corpse.',
          'A Celestial or Fiend visited you in your dreams to give a warning of dangers to come.',
          'You briefly visited the Feywild or Shadowfell.',
          'You saw a portal that you believe leads to another plane of existence.',
          'You were turned into a toad and remained in that form for 1d4 weeks.',
          'You were petrified and remained a stone statue for a time until someone freed you.',
          "You were enslaved by a hag, a satyr, or some other being and lived in that creature's thrall for 1d6 years.",
          'A dragon held you as a prisoner for 1d4 months until adventurers killed it.',
          'You were taken captive by a race of evil humanoids such as drow, kuo-toa, or quaggoths. You lived as a slave in the Underdark until you escaped.',
          'You served a powerful adventurer as a hireling. You have only recently left that service. Use the supplemental tables and work with your DM to determine the basic details about your former employer.',
          'You went insane for 1d6 years and recently regained your sanity. A tic or some other bit of odd behavior might linger.',
          'A lover of yours was secretly a silver dragon.',
          'You were captured by a cult and nearly sacrificed on an altar to the foul being the cultists served. You escaped, but you fear they will find you.',
          'You met a demigod, an archdevil, an archfey, a demon lord, or a titan, and you lived to tell the tale.',
          'You were swallowed by a giant fish and spent a month in its gullet before you escaped.',
          'A powerful being granted you a wish, but you squandered it on something frivolous.',
        ],
        alignment: [
          'Chaotic evil (50%) or chaotic neutral (50%)',
          'Lawful evil',
          'Neutral evil',
          'Neutral',
          'Neutral good',
          'Lawful good (50%) or lawful neutral (50%)',
          'Chaotic good (50%) or chaotic neutral (50%)',
        ],
      },
      life: {
        parents: [
          'You do not know who your parents were.',
          'One parent was your race and the other was a human.',
          'One parent was an elf and the other was your race.',
          'Both parents were your race.',
          'One parent was your race and the other was a half-orc.',
          'One parent was your race and the other was a half-elf.',
          'One parent was your race and the other was a devil.',
          'One parent was a tiefling and the other was your race.',
        ],
        birthplace: [
          'Home',
          'Home of a family friend',
          'Home of a healer or midwife',
          'Carriage, cart, or wagon',
          'Barn, shed, or other outbuilding',
          'Cave',
          'Field',
          'Forest',
          'Temple',
          'Battlefield',
          'Alley or street',
          'Brothel, tavern, or inn',
          'Castle, keep, tower, or palace',
          'Sewer or rubbish heap',
          'Among people of a different race',
          'On board a boat or a ship',
          'In a prison or in the headquarters of a secret organization',
          "In a sage's laboratory",
          'In the Feywild',
          'In the Shadowfell',
          'On the Astral Plane or the Ethereal Plane',
          'On an Inner Plane of your choice',
          'On an Outer Plane of your choice',
        ],
        siblings: [
          'None',
          'One, older',
          'One, younger',
          'Two, older',
          'Two, younger',
          'Three, older',
          'Three, younger',
        ],
        friends: [
          "Sadly you can't recall anybody",
          'Institution, such as an asylum',
          'Temple',
          'Orphanage',
          'Guardian',
          'Paternal or maternal aunt, uncle, or both',
          'Paternal or maternal grandparent(s)',
          'Adoptive family (same or different race)',
          'Single father or stepfather',
          'Single mother or stepmother',
          'Mother and father',
        ],
        lifestyle: [
          'Wretched (-40)',
          'Squalid (-20)',
          'Poor (-10)',
          'Modest (+0)',
          'Comfortable (+10)',
          'Wealthy (+20)',
          'Aristocratic (+40)',
        ],
        home: [
          'On the streets',
          'Rundown shack',
          'No permanent residence',
          'Encampment or village in the wilderness',
          'Apartment in a rundown neighborhood',
          'Small house',
          'Large house',
          'Mansion',
          'Palace or castle',
        ],
      },
      race: {
        Aarakocra: {
          age: {
            mature: 3,
            max: 30,
          },
          source: ['DMG, page 282', 'EEPC, page 5. Also found in EGW, page 165.'],
        },
        Aasimar: {
          age: {
            mature: 20,
            max: 160,
          },
          source: [
            'DMG, page 286',
            'MPMM, page 7',
            'VGM, page 104. Also found in EGW, page 166',
          ],
        },
        Bugbear: {
          age: {
            mature: 16,
            max: 80,
          },
          source: [
            'ERLW, page 25.',
            'MPMM, page 8',
            'VGM, page 119. Also found in EGW, page 174.',
          ],
        },
        Bullywug: {
          age: {
            mature: 18,
            max: 60,
          },
          source: ['DMG, page 282'],
        },
        Centaur: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['GGR, page 15.', 'MOT, page 18.', 'MPMM, page 9'],
        },
        Changeling: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['ERLW, page 17. Also found in WGE, page 60.', 'MPMM, page 10'],
        },
        'Custom Lineage': {
          age: {
            mature: 18,
            max: 100,
          },
          source: ['TCE, page 8'],
        },
        'Deep Gnome': {
          age: {
            mature: 18,
            max: 500,
          },
          source: ['MPMM, page 11'],
        },
        Dhampir: {
          age: {
            mature: 1,
            max: 750,
          },
          source: ['VRGR, page 16'],
        },
        Dragonborn: {
          age: {
            mature: 15,
            max: 80,
          },
          source: ['PHB, page 32.', 'FTD, page 10', 'EGW, page 168'],
        },
        Duergar: {
          age: {
            mature: 18,
            max: 350,
          },
          source: ['MPMM, page 12'],
        },
        Dwarf: {
          age: {
            mature: 20,
            max: 350,
          },
          source: [
            'PHB, page 18',
            'MTF, page 81. Also found in SCAG, page 104.',
            'ERLW, page 51. Also found in WGE, page 108.',
          ],
        },
        Eladrin: {
          age: {
            mature: 100,
            max: 750,
          },
          source: ['MPMM, page 13'],
        },
        Elf: {
          age: {
            mature: 100,
            max: 750,
          },
          source: [
            'PHB, page 21.',
            'PHB, page 24',
            'DMG, page 286',
            'MTF, page 61.',
            'PHB, page 23.',
            'ERLW, page 49. Also found in WGE, page 105.',
            'EGW, page 21',
            'MTF, page 62. Also found in EGW, page 163.',
          ],
        },
        Fairy: {
          age: {
            mature: 1,
            max: 1000,
          },
          source: ['MPMM, page 14', 'WBtW, page 12.'],
        },
        Firbolg: {
          age: {
            mature: 30,
            max: 500,
          },
          source: ['MPMM, page 15', 'VGM, page 107. Also found in EGW, page 169.'],
        },
        Genasi: {
          age: {
            mature: 20,
            max: 120,
          },
          source: ['EEPC, page 9. Also found in EGW, page 170.', 'MPMM, page 16'],
        },
        Gith: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MTF, page 96'],
        },
        Githyanki: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MPMM, page 18'],
        },
        Githzerai: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MPMM, page 19'],
        },
        Gnoll: {
          age: {
            mature: 8,
            max: 60,
          },
          source: ['DMG, page 282'],
        },
        Gnome: {
          age: {
            mature: 40,
            max: 500,
          },
          source: [
            'PHB, page 35',
            'MTF, page 113.',
            'DMG, page 282',
            'SCAG, page 115. Also found in EEPC, page 5.',
            'PHB, page 37',
            'ERLW, page 47. Also found in WGE, page 103.',
          ],
        },
        Goblin: {
          age: {
            mature: 8,
            max: 60,
          },
          source: [
            'DMG, page 282',
            'ERLW, page 26.',
            'GGR, page 16.',
            'MPMM, page 20',
            'VGM, page 119.  Also found in EGW, page 174.',
          ],
        },
        Goliath: {
          age: {
            mature: 20,
            max: 100,
          },
          source: [
            'MPMM, page 21',
            'VGM, page 108. Also found in EEPC, page 10; EGW, page 175; IDRotF.',
          ],
        },
        Grimlock: {
          age: {
            mature: 1,
            max: 50,
          },
          source: ['DMG, page 282'],
        },
        'Half-Elf': {
          age: {
            mature: 20,
            max: 180,
          },
          source: [
            'PHB, page 38.',
            'SCAG, page 116',
            'ERLW, page 40. Also found in WGE, page 96.',
            'ERLW, page 50. Also found in WGE, page 106.',
          ],
        },
        'Half-Orc': {
          age: {
            mature: 14,
            max: 75,
          },
          source: ['PHB, page 40.', 'ERLW, page 41. Also found in WGE, page 98.'],
        },
        Halfling: {
          age: {
            mature: 20,
            max: 250,
          },
          source: [
            'PHB, page 26.',
            'SCAG, page 110',
            'PHB, page 28.',
            'EGW, page 164',
            'ERLW, page 43. Also found in WGE, page 99.',
            'ERLW, page 44. Also found in WGE, page 100.',
          ],
        },
        Harengon: {
          age: {
            mature: 1,
            max: 1000,
          },
          source: ['MPMM, page 22', 'WBtW, page 13.'],
        },
        Hexblood: {
          age: {
            mature: 1,
            max: 1000,
          },
          source: ['VRGR, page 18'],
        },
        Hobgoblin: {
          age: {
            mature: 20,
            max: 100,
          },
          source: [
            'DMG, page 282',
            'ERLW, page 26.',
            'MPMM, page 23',
            'VGM, page 119. Also found in EGW, page 175.',
          ],
        },
        Human: {
          age: {
            mature: 20,
            max: 100,
          },
          source: [
            'PHB, page 29.',
            'ERLW, page 41',
            'ERLW, page 42. Also found in WGE, page 98.',
            'ERLW, page 45. Also found in WGE, page 101.',
            'ERLW, page 46. Also found in WGE, page 102.',
            'ERLW, page 48. Also found in WGE, page 104.',
            'PHB, page 31',
          ],
        },
        Kalashtar: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['ERLW, page 29. Also found in WGE, page 62.'],
        },
        Kenku: {
          age: {
            mature: 12,
            max: 60,
          },
          source: [
            'DMG, page 282.',
            'MPMM, page 24',
            'VGM, page 109. Also found in EGW, page 177.',
          ],
        },
        Kobold: {
          age: {
            mature: 6,
            max: 120,
          },
          source: ['DMG, page 282', 'MPMM, page 25', 'VGM, page 119.'],
        },
        'Kuo-Toa': {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['DMG, page 282'],
        },
        Leonin: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MOT, page 20'],
        },
        Lizardfolk: {
          age: {
            mature: 14,
            max: 80,
          },
          source: ['DMG, page 282', 'MPMM, page 26', 'VGM, page 111.'],
        },
        Loxodon: {
          age: {
            mature: 20,
            max: 450,
          },
          source: ['GGR, page 17'],
        },
        Merfolk: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['DMG, page 282'],
        },
        Minotaur: {
          age: {
            mature: 17,
            max: 150,
          },
          source: ['GGR, page 18.', 'MOT, page 22.', 'MPMM, page 27'],
        },
        Orc: {
          age: {
            mature: 12,
            max: 50,
          },
          source: [
            'DMG, page 282',
            'EGW, page 178.',
            'ERLW, page 31.',
            'MPMM, page 28',
            'VGM, page 120.',
          ],
        },
        Owlin: {
          age: {
            mature: 20,
            max: 450,
          },
          source: ['SCC, page 29'],
        },
        Reborn: {
          age: {
            mature: 1,
            max: 1000,
          },
          source: ['VRGR, page 20'],
        },
        Satyr: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MOT, page 24.', 'MPMM, page 29'],
        },
        'Sea Elf': {
          age: {
            mature: 80,
            max: 750,
          },
          source: ['MPMM, page 30'],
        },
        'Shadar-Kai': {
          age: {
            mature: 20,
            max: 750,
          },
          source: ['MPMM, page 31'],
        },
        Shifter: {
          age: {
            mature: 10,
            max: 70,
          },
          source: ['ERLW, page 33. Also found in WGE, page 64.', 'MPMM, page 32'],
        },
        'Simic Hybrid': {
          age: {
            mature: 1,
            max: 500,
          },
          source: ['GGR, page 20'],
        },
        Skeleton: {
          age: {
            mature: 1,
            max: 1000,
          },
          source: ['DMG, page 282'],
        },
        Tabaxi: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MPMM, page 33', ' VGM, page 113. Also found in EGW, page 179.'],
        },
        Tiefling: {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['PHB, page 42.', 'MTF, page 21', 'SCAG, page 118'],
        },
        Tortle: {
          age: {
            mature: 15,
            max: 50,
          },
          source: ['MPMM, page 34'],
        },
        Triton: {
          age: {
            mature: 15,
            max: 200,
          },
          source: ['MOT, page 26.', 'MPMM, page 35', 'VGM, page 115.'],
        },
        Troglodyte: {
          age: {
            mature: 16,
            max: 300,
          },
          source: ['DMG, page 282'],
        },
        Vedalken: {
          age: {
            mature: 40,
            max: 500,
          },
          source: ['GGR, page 21'],
        },
        Verdan: {
          age: {
            mature: 24,
            max: 200,
          },
          source: ['AI, page 72'],
        },
        Warforged: {
          age: {
            mature: 2,
            max: 30,
          },
          source: ['ERLW, page 35. Also found in WGE, page 67.'],
        },
        'Yuan-Ti': {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['MPMM, page 36'],
        },
        'Yuan-ti Pureblood': {
          age: {
            mature: 20,
            max: 100,
          },
          source: ['VGM, page 120.'],
        },
        Zombie: {
          age: {
            mature: 1,
            max: 1000,
          },
          source: ['DMG, page 282'],
        },
      },
      secrets: {
        Doppelganger:
          "I'm a shapechanger. I have none of the traits of the race I'm imitating, but I retain my class features, background, and alignment. I have darkvision out to a range of 60 feet. I can use an action to do either of the following at will: I can innately cast detect thoughts, requiring no components. My spellcasting ability is Intelligence. The spell's Wisdom save DC is 8 + my proficiency bonus + my Intelligence modifier. I can polymorph into any humanoid I have seen or back into my true form. My statistics, other than my size, don't change. Any equipment I'm wearing or carrying isn't transformed. I revert to my true form when I die.",
        'Drizzt Fan':
          "I once met the famous drow ranger Drizzt Do'Urden! In fact, I have a tattered piece of his famous green cloak and would never think to part with it.",
        'Elusive Paramour':
          "A wealthy pasha in Calimshan has placed a bounty on my head for seducing his favorite concubine. Bounty hunters are scouring the Sword Coast in search of me, but I hope they'll never think to look in my town.",
        'Escaped Prisoner':
          "I was brought here from another world by spacefaring mind flayers. The ship in which I was imprisoned crashed in the mountains south of Ten-Towns. After surviving the crash, I nearly froze to death crossing the tundra to reach Ten-Towns. If some friendly trappers hadn't found me, I would have perished. I fear some of my captors also survived the crash and might come looking for me.",
        'Littlest Yeti':
          'I was raised by yeti. Although I relied on my ferocious guardians for food and warmth and never quite adapted to the cold, I speak Yeti and have advantage on Charisma checks made to influence yeti or improve their attitudes.',
        'Midwinter Child':
          'Auril the Frostmaiden has blessed me, for I was born on the Midwinter holiday. I have resistance to cold damage.',
        'Old Flame':
          "I have a lover in Ten-Towns whom I haven't seen in years. At any time outside of combat, I can decide who the lover is by choosing an NPC in Ten-Towns that I can see. Once I make this choice, I can't change it. This old flame is friendly and helpful toward me, even if our past is checkered.",
        'Orc Stone':
          'I saved the life of an orc, who gave me a stone with the symbol of the Many-Arrows tribe (a humanoid skull pierced by three arrows) carved into it. The stone is an uncommon magic item that requires attunement, and only I can attune to it. As an action, I can use the stone to summon the spirit of an orc warrior, which appears within 30 feet of me. The spirit uses the orc war chief stat block in the Monster Manual and disappears after 10 minutes or when reduced to 0 hit points. The spirit understands any language I speak and obeys my commands. After the stone is used three times, it turns to dust.',
        'Owlbear Whisperer':
          "Owlbears are predisposed to like me. If I am within 10 feet of an owlbear, I can use an action to make a DC 10 Charisma (Animal Handling) check. On a success, I change the owlbear's attitude toward me from hostile to indifferent or from indifferent to friendly.",
        'Pirate Cannibal':
          'I served aboard Dark Duchess, a pirate ship from the city of Luskan. After the vessel got stuck in the ice, everyone but the captain abandoned the vessel and fled to Ten-Towns. We got lost in a blizzard along the way. I was the only one who made it, and only by eating my mates. The ship and its treasure are still out there.',
        Reincarnation:
          "I died and was brought back to life by a friendly human druid using the reincarnate spell. I have no idea what became of the druid, whose name I don't know. I retain the memories of my previous life, some or all of which was spent in Icewind Dale. (Roll on the table in the spell's description to determine your character's previous race, or choose a race from the table that you like, then flesh out the story of your previous life.)",
        'Ring Hunter':
          "I am looking for the knucklehead trout that bit off my father's finger, which had a signet ring on it. To preserve my inheritance, I must retrieve the lost ring.",
        'Runaway Author':
          "I penned a notorious exposé called The Hellbent Highborn, which accused several prominent patriars in Baldur's Gate and nobles in Waterdeep of being devil worshipers. Although my accusations were well founded, I made a lot of enemies and was forced to seek refuge in this town.",
        'Slaad Host':
          "A red slaad implanted a pellet-sized egg in me shortly before I started my adventuring career. If I can't get rid of it in the next two months, the egg will gestate inside me, and a slaad tadpole will burst from my chest, killing me. It will then quickly grow into an adult slaad and kill even more people.",
        Spy: "I'm a spy for the Harpers, a secretive organization that works behind the scenes to thwart tyrants and other evildoers. My mission in Icewind Dale is to safeguard the settlements of Ten-Towns while concealing my Harper affiliation. Credible threats to Ten-Towns include the Arcane Brotherhood, an organization of wizards based in Luskan, and the Zhentarim, an expansive shadow network that wants to control trade throughout the North. Both have threatened Ten-Towns in the past. My only Harper contact in Ten-Towns is a human named Beldora, who poses as a homeless woman and spends her days gathering information in Bryn Shander.",
      },
      traitsIdealsBondsFlaws: {
        traits: [
          "I idolize a particular hero of my faith and constantly refer to that person's deeds and example.",
          'I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.',
          'I see omens in every event and action. The gods try to speak to us, we just need to listen.',
          'Nothing can shake my optimistic attitude.',
          'I quote (or misquote) the sacred texts and proverbs in almost every situation.',
          'I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.',
          "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
          "I've spent so long in the temple that I have little practical experience dealing with people in the outside world.",
          'I fall in and out of love easily, and am always pursuing someone.',
          'I have a joke for every occasion, especially occasions where humor is inappropriate.',
          'Flattery is my preferred trick for getting what I want.',
          "I'm a born gambler who can't resist taking a risk for a potential payoff.",
          "I lie about almost everything, even when there's no good reason to.",
          'Sarcasm and insults are my weapons of choice.',
          'I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.',
          'I pocket anything I see that might have some value.',
          'I always have plan for what to do when things go wrong.',
          'I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.',
          'The first thing I do in a new place is note the locations of everything valuable--or where such things could be hidden.',
          'I would rather make a new friend than a new enemy.',
          'I am incredibly slow to trust. Those who seem the fairest often have the most to hide.',
          "I don't pay attention to the risks in a situation. Never tell me the odds.",
          "The best way to get me to do something is to tell me I can't do it.",
          'I blow up at the slightest insult.',
          'I know a story relevant to almost every situation.',
          'Whenever I come to a new place, I collect local rumors and spread gossip.',
          "I'm a hopeless romantic, always searching for that 'special someone'.",
          'Nobody stays angry at me or around me for long, since I can defuse any amount of tension.',
          'I love a good insult, even one directed at me.',
          "I get bitter if I'm not the center of attention.",
          "I'll settle for nothing less than perfection.",
          'I change my mood or my mind as quickly as I change key in a song.',
          'I judge people by their actions, not their words.',
          "If someone is in trouble, I'm always willing to lend help.",
          'When I set my mind to something, I follow through no matter what gets in my way.',
          'I have a strong sense of fair play and always try to find the most equitable solution to arguments.',
          "I'm confident in my own abilities and do what I can to instill confidence in others.",
          'Thinking is for other people. I prefer action.',
          'I misuse long words in an attempt to sound smarter.',
          'I get bored easily. When am I going to get on with my destiny.',
          "I believe that everything worth doing is worth doing right. I can't help it--I'm a perfectionist.",
          "I'm a snob who looks down on those who can't appreciate fine art.",
          'I always want to know how things work and what makes people tick.',
          "I'm full of witty aphorisms and have a proverb for every occasion.",
          "I'm rude to people who lack my commitment to hard work and fair play.",
          'I like to talk at length about my profession.',
          "I don't part with my money easily and will haggle tirelessly to get the best deal possible.",
          "I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.",
          "I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.",
          'I am utterly serene, even in the face of disaster.',
          'The leader of my community has something wise to say on every topic, and I am eager to share that wisdom.',
          'I feel tremendous empathy for all who suffer.',
          "I'm oblivious to etiquette and social expectations.",
          'I connect everything that happens to me to a grand cosmic plan.',
          'I often get lost in my own thoughts and contemplations, becoming oblivious to my surroundings.',
          'I am working on a grand philosophical theory and love sharing my ideas.',
          'My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.',
          'The common folk love me for my kindness and generosity.',
          'No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.',
          'I take great pains to always look my best and follow the latest fashions.',
          "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.",
          'Despite my birth, I do not place myself above other folk. We all have the same blood.',
          'My favor, once lost, is lost forever.',
          'If you do me an injury, I will crush you, ruin your name, and salt your fields.',
          "I'm driven by a wanderlust that led me away from home.",
          'I watch over my friends as if they were a litter of newborn pups.',
          "I once ran twenty-five miles without stopping to warn my clan of an approaching orc horde. I'd do it again if I had to.",
          'I have a lesson for every situation, drawn from observing nature.',
          "I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.",
          "I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.",
          'I feel far more comfortable around animals than people.',
          'I was, in fact, raised by wolves.',
          'I use polysyllabic words to convey the impression of great erudition.',
          "I've read every book in the world's greatest libraries--or like to boast that I have.",
          "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.",
          "There's nothing I like more than a good mystery.",
          "I'm willing to listen to every side of an argument before I make my own judgment.",
          'I...speak...slowly...when talking...to idiots...which...almost...everyone...is...compared...to me.',
          'I am horribly, horribly awkward in social situations.',
          "I'm convinced that people are always trying to steal my secrets.",
          'My friends know they can rely on me, no matter what.',
          'I work hard so that I can play hard when the work is done.',
          'I enjoy sailing into new ports and making new friends over a flagon of ale.',
          'I stretch the truth for the sake of a good story.',
          'To me, a tavern brawl is a nice way to get to know a new city.',
          'I never pass up a friendly wager.',
          'My language is as foul as an otyugh nest.',
          'I like a job well done, especially if I can convince someone else to do it.',
          "I'm always polite and respectful.",
          "I'm haunted by memories of war. I can't get the images of violence out of my mind.",
          "I've lost too many friends, and I'm slow to make new ones.",
          "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.",
          'I can stare down a hellhound without flinching.',
          'I enjoy being strong and like breaking things.',
          'I have a crude sense of humor.',
          'I face problems head-on. A simple direct solution is the best path to success.',
          'I hide scraps of food and trinkets away in my pockets.',
          'I ask a lot of questions.',
          'I like to squeeze into small places where no one else can get to me.',
          'I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.',
          'I eat like a pig and have bad manners.',
          "I think anyone who's nice to me is hiding evil intent.",
          "I don't like to bathe.",
          'I bluntly say what other people are hinting or hiding.',
        ],
        ideals: [
          'Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well.',
          'Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld.',
          'Charity. I always try to help those in need, no matter what the personal cost.',
          'Change. We must help bring about the changes the gods are constantly working in the world.',
          "Power. I hope to one day rise to the top of my faith's religious hierarchy.",
          "Aspiration. I seek to prove my self worthy of my god's favor by matching my actions against his or her teachings.",
          'Independence. I am a free spirit--no one tells me what to do.',
          "Fairness. I never target people who can't afford to lose a few coins.",
          'Charity. I distribute money I acquire to the people who really need it.',
          'Creativity. I never run the same con twice.',
          'Friendship. Material goods come and go. Bonds of friendship last forever.',
          "Aspiration. I'm determined to make something of myself.",
          "Honor. I don't steal from others in the trade.",
          'Freedom. Chains are meant to be broken, as are those who would forge them.',
          'Charity. I steal from the wealthy so that I can help people in need.',
          'Greed. I will do whatever it takes to become wealthy.',
          "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care.",
          "Redemption. There's a spark of good in everyone.",
          'Beauty. When I perform, I make the world better than it was.',
          'Tradition. The stories, legends, and songs of the past must never be forgotten.',
          'Creativity. The world is in need of new ideas and bold action.',
          "Greed. I'm only in it for the money and fame.",
          "People. I like seeing the smiles on people's faces when I perform. That's all that matters.",
          'Honesty. Art should reflect the soul; it should come from within and reveal who we really are.',
          'Respect. People deserve to be treated with dignity and respect.',
          'Fairness. No one should get preferential treatment before the law, and no one is above the law.',
          'Freedom. Tyrants must not be allowed to oppress the people.',
          'Might. If I become strong, I can take what I want--what I deserve.',
          "Sincerity. There's no good pretending to be something I'm not.",
          'Destiny. Nothing and no one can steer me away from my higher calling.',
          'Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization.',
          'Generosity. My talents were given to me so that I could use them to benefit the world.',
          'Freedom. Everyone should be free to pursue his or her livelihood.',
          "Greed. I'm only in it for the money.",
          "People. I'm committed to the people I care about, not to ideals.",
          'Aspiration. I work hard to be the best there is at my craft.',
          'Greater Good. My gifts are meant to be shared with all, not used for my own benefit.',
          'Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking.',
          'Free Thinking. Inquiry and curiosity are the pillars of progress.',
          'Power. Solitude and contemplation are paths toward mystical or magical power.',
          'Live and Let Live. Meddling in the affairs of others only causes trouble.',
          "Self-Knowledge. If you know yourself, there're nothing left to know.",
          'Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity.',
          'Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine.',
          'Independence. I must prove that I can handle myself without the coddling of my family.',
          'Power. If I can attain more power, no one will tell me what to do.',
          'Family. Blood runs thicker than water.',
          'Noble Obligation. It is my duty to protect and care for the people beneath me.',
          'Change. Life is like the seasons, in constant change, and we must change with it.',
          "Greater Good. It is each person's responsibility to make the most happiness for the whole tribe.",
          'Honor. If I dishonor myself, I dishonor my whole clan.',
          'Might. The strongest are meant to rule.',
          'Nature. The natural world is more important than all the constructs of civilization.',
          'Glory. I must earn glory in battle, for myself and my clan.',
          'Knowledge. The path to power and self-improvement is through knowledge.',
          'Beauty. What is beautiful points us beyond itself toward what is true.',
          'Logic. Emotions must not cloud our logical thinking.',
          'No Limits. Nothing should fetter the infinite possibility inherent in all existence.',
          'Power. Knowledge is the path to power and domination.',
          'Self-improvement. The goal of a life of study is the betterment of oneself.',
          'Respect. The thing that keeps a ship together is mutual respect between captain and crew.',
          'Fairness. We all do the work, so we all share in the rewards.',
          'Freedom. The sea is freedom--the freedom to go anywhere and do anything.',
          "Master. I'm a predator, and the other ships on the sea are my prey.",
          "People. I'm committed to my crewmates, not to ideals.",
          "Aspiration. Someday I'll own my own ship and chart my own destiny.",
          'Greater Good. Our lot is to lay down our lives in defense of others.',
          'Responsibility. I do what I must and obey just authority.',
          'Independence. When people follow orders blindly they embrace a kind of tyranny.',
          'Might. In life as in war, the stronger force wins.',
          "Ideals aren't worth killing for or going to war for. ",
          'Nation. My city, nation, or people are all that matter.',
          'Respect. All people, rich or poor, deserve respect.',
          'Community. We have to take care of each other, because no one else is going to do it.',
          'Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things.',
          'Retribution. The rich need to be shown what life and death are like in the gutters.',
          "People. I help people who help me--that's what keeps us alive.",
          "Aspiration. I'm going to prove that I'm worthy of a better life.",
        ],
        bonds: [
          'I would die to recover an ancient artifact of my faith that was lost long ago.',
          'I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.',
          'I owe me life to the priest who took me in when my parents died.',
          'Everything I do is for the common people.',
          'I will do anything to protect the temple where I served.',
          'I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.',
          'I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.',
          "I owe everything to my mentor--a horrible person who's probably rotting in jail somewhere.",
          "Somewhere out there I have a child who doesn't know me. I'm making the world better for him or her.",
          "I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.",
          "A powerful person killed someone I love. Some day soon, I'll have my revenge.",
          "I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.",
          "I'm trying to pay off an old debt I owe to a generous benefactor.",
          'My ill-gotten gains go to support my family.',
          'Something important was taken from me, and I aim to steal it back.',
          'I will become the greatest thief that ever lived.',
          "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
          'Someone I loved died because of a mistake I made. That will never happen again.',
          'My instrument is my most treasured possession, and it reminds me of someone I love.',
          "Someone stole my precious instrument, and someday I'll get it back.",
          'I want to be famous, whatever it takes.',
          "I idolize a hero of the old tales and measure my deeds against that person's.",
          'I will do anything to prove myself superior to me hated rival.',
          'I would do anything for the other members of my old troupe.',
          'I have a family, but I have no idea where they are. One day, I hope to see them again.',
          'I worked the land, I love the land, and I will protect the land.',
          'A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.',
          'My tools are symbols of my past life, and I carry them so that I will never forget my roots.',
          'I protect those who cannot protect themselves.',
          'I wish my childhood sweetheart had come with me to pursue my destiny.',
          'The workshop where I learned my trade is the most important place in the world to me.',
          "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.",
          'I owe my guild a great debt for forging me into the person I am today.',
          "I pursue wealth to secure someone's love.",
          'One day I will return to my guild and prove that I am the greatest artisan of them all.',
          'I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.',
          'Nothing is more important than the other members of my hermitage, order, or association.',
          'I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.',
          "I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.",
          'I entered seclusion because I loved someone I could not have.',
          'Should my discovery come to light, it could bring ruin to the world.',
          'My isolation gave me great insight into a great evil that only I can destroy.',
          'I will face any challenge to win the approval of my family.',
          "My house's alliance with another noble family must be sustained at all costs.",
          'Nothing is more important that the other members of my family.',
          'I am in love with the heir of a family that my family despises.',
          'My loyalty to my sovereign is unwavering.',
          'The common folk must see me as a hero of the people.',
          'My family, clan, or tribe is the most important thing in my life, even when they are far from me.',
          'An injury to the unspoiled wilderness of my home is an injury to me.',
          'I will bring terrible wrath down on the evildoers who destroyed my homeland.',
          'I am the last of my tribe, and it is up to me to ensure their names enter legend.',
          'I suffer awful visions of a coming disaster and will do anything to prevent it.',
          'It is my duty to provide children to sustain my tribe.',
          'It is my duty to protect my students.',
          'I have an ancient text that holds terrible secrets that must not fall into the wrong hands.',
          'I work to preserve a library, university, scriptorium, or monastery.',
          "My life's work is a series of tomes related to a specific field of lore.",
          "I've been searching my whole life for the answer to a certain question.",
          'I sold my soul for knowledge. I hope to do great deeds and win it back.',
          "I'm loyal to my captain first, everything else second.",
          'The ship is most important--crewmates and captains come and go.',
          "I'll always remember my first ship.",
          'In a harbor town, I have a paramour whose eyes nearly stole me from the sea.',
          'I was cheated of my fair share of the profits, and I want to get my due.',
          'Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.',
          'I would lay down my life for the people I served with.',
          'Someone saved my life on the battlefield. To this day, I will never leave a friend behind.',
          'My honor is my life.',
          "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.",
          'Those who fight beside me are those worth dying for.',
          'I fight for those who cannot fight for themselves.',
          "My town or city is my home, and I'll fight to defend it.",
          'I sponsor an orphanage to keep others from enduring what I was forced to endure.',
          'I owe my survival to another urchin who taught me to live on the streets.',
          'I owe a debt I can never repay to the person who took pity on me.',
          "I escaped my life of poverty by robbing an important person, and I'm wanted for it.",
          "No one else is going to have to endure the hardships I've been through.",
        ],
        flaws: [
          'I judge others harshly, and myself even more severely.',
          "I put too much trust in those who wield power within my temple's hierarchy.",
          'My piety sometimes leads me to blindly trust those that profess faith in my god.',
          'I am inflexible in my thinking.',
          'I am suspicious of strangers and suspect the worst of them.',
          'Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.',
          "I can't resist a pretty face.",
          "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.",
          "I'm convinced that no one could ever fool me in the way I fool others.",
          "I'm too greedy for my own good. I can't resist taking a risk if there's money involved.",
          "I can't resist swindling people who are more powerful than me.",
          "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.",
          "When I see something valuable, I can't think about anything but how to steal it.",
          'When faced with a choice between money and my friends, I usually choose the money.',
          "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
          "I have a 'tell' that reveals when I'm lying.",
          'I turn tail and run when things go bad.',
          "An innocent person is in prison for a crime that I committed. I'm okay with that.",
          "I'll do anything to win fame and renown.",
          "I'm a sucker for a pretty face.",
          'A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.',
          'I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.',
          'I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.',
          'Despite my best efforts, I am unreliable to my friends.',
          'The tyrant who rules my land will stop at nothing to see me killed.',
          "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.",
          'The people who knew me when I was young know my shameful secret, so I can never go home again.',
          'I have a weakness for the vices of the city, especially hard drink.',
          'Secretly, I believe that things would be better if I were a tyrant lording over the land.',
          'I have trouble trusting in my allies.',
          "I'll do anything to get my hands on something rare or priceless.",
          "I'm quick to assume that someone is trying to cheat me.",
          'No one must ever learn that I once stole money from guild coffers.',
          "I'm never satisfied with what I have--I always want more.",
          'I would kill to acquire a noble title.',
          "I'm horribly jealous of anyone who outshines my handiwork. Everywhere I go, I'm surrounded by rivals.",
          "Now that I've returned to the world, I enjoy its delights a little too much.",
          'I harbor dark bloodthirsty thoughts that my isolation failed to quell.',
          'I am dogmatic in my thoughts and philosophy.',
          'I let my need to win arguments overshadow friendships and harmony.',
          "I'd risk too much to uncover a lost bit of knowledge.",
          "I like keeping secrets and won't share them with anyone.",
          'I secretly believe that everyone is beneath me.',
          'I hide a truly scandalous secret that could ruin my family forever.',
          "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.",
          'I have an insatiable desire for carnal pleasures.',
          'In fact, the world does revolve around me.',
          'By my words and actions, I often bring shame to my family.',
          'I am too enamored of ale, wine, and other intoxicants.',
          "There's no room for caution in a life lived to the fullest.",
          "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.",
          'I am slow to trust members of other races',
          'Violence is my answer to almost any challenge.',
          "Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.",
          'I am easily distracted by the promise of information.',
          'Most people scream and run when they see a demon. I stop and take notes on its anatomy.',
          'Unlocking an ancient mystery is worth the price of a civilization.',
          'I overlook obvious solutions in favor of complicated ones.',
          'I speak without really thinking through my words, invariably insulting others.',
          "I can't keep a secret to save my life, or anyone else's.",
          "I follow orders, even if I think they're wrong.",
          "I'll say anything to avoid having to do extra work.",
          'Once someone questions my courage, I never back down no matter how dangerous the situation.',
          "Once I start drinking, it's hard for me to stop.",
          "I can't help but pocket loose coins and other trinkets I come across.",
          'My pride will probably lead to my destruction',
          'The monstrous enemy we faced in battle still leaves me quivering with fear.',
          'I have little respect for anyone who is not a proven warrior.',
          'I made a terrible mistake in battle that cost many lives--and I would do anything to keep that mistake secret.',
          'My hatred of my enemies is blind and unreasoning.',
          'I obey the law, even if the law causes misery.',
          "I'd rather eat my armor than admit when I'm wrong.",
          "If I'm outnumbered, I always run away from a fight.",
          "Gold seems like a lot of money to me, and I'll do just about anything for more of it.",
          'I will never fully trust anyone other than myself.',
          "I'd rather kill someone in their sleep than fight fair.",
          "It's not stealing if I need it more than someone else.",
          "People who don't take care of themselves get what they deserve.",
        ],
      },
    };
    return dnData;
  });
